### ISSUE TITLE
Position data discrepancy

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#964]
# Issue

There appears to be a discrepancy in the position statistics related to quantity, price and value.

## Details

See [discord thread](https://discord.com/channels/888448459168948284/1249802776817565886/1249802778285441127) for full background.

While getting feedback on a new table-based design for position details, @tsorro noted that the change in value for the position didn't seem to accurately reflect the expected value based on the quantity and price change:

> ![image](https://github.com/tradingstrategy-ai/trade-executor/assets/35901/9d92afdb-729a-4811-ae40-3f11a5714cc7)
> Is this math correct?
> How can the position value delta (-20.63) be smaller than the underlying asset price delta (-78.77) when multiplier (quantity) is 1.28?
> Maybe my own math is wrong 😄

The position in question is:
https://tradingstrategy.ai/strategies/enzyme-polygon-eth-breakout/closed-positions/6

The source of data for each of the metrics in the above table is identified below (from the `state` endpoint for this strategy):

| Type | Open | Close |
| --- | --- | --- |
| Executed | `portfolio.closed_positions.6.opened_at` | `portfolio.closed_positions.6.closed_at` | 
| Quantity | `stats.position.6[0].quantity`<br>(from first stats entry for position) | `stats.position.6.at(-2).quantity`<br>(from second-to-last stats entry for position) | 
| Price | `portfolio.closed_positions.6.trades.11.executed_price`<br>(from position's first trade) | `portfolio.closed_positions.6.trades.12.executed_price`<br>(from position's last trade) | 
| Value | `stats.position.6[0].value`<br>(from first stats entry for position)  | `stats.position.6.at(-2).value`<br>(from second-to-last stats entry for position) |

**Comment by AlexTheLion123** [comment]
After further inspection, it appears that `TradingPosition.get_value()`, which is used to calculate the metrics in the `Value` row, can return incorrect results since it is a [planned value](https://github.com/tradingstrategy-ai/trade-executor/blob/cae1ae9abe9f08b7b4ae0caf38efa1ca4e7d28)

Therefore, @kenkunz, we can switch to using the value from the 

i.e. the value circled in red here is correct

![tradingstrategy ai_strategies_enzyme-polygon-eth-breakout_closed-positions_6](https://github.com/tradingstrategy-ai/trade-executor/assets/74208897/0da976a1-f0ad-4973-8791-652b7e48b2e2)
15/tradeexecutor/state/position.py#L111-L121).
